In [1]:
import tensorflow as tf

In [2]:
print (tf.__version__)

1.3.0


In [8]:
hello = tf.constant("Hello ")

In [9]:
world = tf.constant("World")

In [10]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [13]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [14]:
print (result)

b'Hello World'


 # Addition 


In [16]:
a = tf.constant(10)

In [17]:
b = tf.constant(20)

In [18]:
type(a)

tensorflow.python.framework.ops.Tensor

In [19]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [20]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [21]:
result

30

In [28]:
 const = tf.constant(10)

In [29]:
fill_mat = tf.fill((3,3),10)

In [30]:
myzeros = tf.zeros((4,4))

In [31]:
myones =tf.ones((4,4))

In [32]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [33]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [34]:
myops= [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [35]:
sess = tf.InteractiveSession()

In [39]:
for op in myops:
    print(op.eval())
    

10
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.39710984  0.79442406 -1.0618211  -0.24590415]
 [-0.65640271 -0.18191482 -0.29131594  0.19462988]
 [ 0.24198531 -0.86113894  0.30768412 -0.33037859]
 [ 0.25226542  0.83106315 -0.3520579   0.53936595]]
[[ 0.49767804  0.56198609  0.10124087  0.24425542]
 [ 0.68286753  0.92030406  0.67571557  0.48013473]
 [ 0.42902339  0.0417881   0.24042547  0.97011328]
 [ 0.14021873  0.1006583   0.6218313   0.18500149]]
